version: "3"
services:
  fastify:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: fastify
    working_dir: /home/app
    volumes:
      - .:/home/app
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run dev"
