version: "3"
services:
  fastify:
    build:
      context: .
    container_name: fastify
    working_dir: /home/app
    volumes:
      - .:/home/app
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run dev"
  redis:
    image: redis:alpine
    ports:
      - "10000:6379"
